
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EASLoginProxyService", targetNamespace = "http://10.99.10.62:6888/ormrpc/services/EASLogin", wsdlLocation = "file:/E:/testDemo/EASLogin.wsdl")
public class EASLoginProxyService
    extends Service
{

    private final static URL EASLOGINPROXYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservice.EASLoginProxyService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservice.EASLoginProxyService.class.getResource(".");
            url = new URL(baseUrl, "file:/E:/testDemo/EASLogin.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/testDemo/EASLogin.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        EASLOGINPROXYSERVICE_WSDL_LOCATION = url;
    }

    public EASLoginProxyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EASLoginProxyService() {
        super(EASLOGINPROXYSERVICE_WSDL_LOCATION, new QName("http://10.99.10.62:6888/ormrpc/services/EASLogin", "EASLoginProxyService"));
    }

    /**
     * 
     * @return
     *     returns EASLoginProxy
     */
    @WebEndpoint(name = "EASLogin")
    public EASLoginProxy getEASLogin() {
        return super.getPort(new QName("http://10.99.10.62:6888/ormrpc/services/EASLogin", "EASLogin"), EASLoginProxy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EASLoginProxy
     */
    @WebEndpoint(name = "EASLogin")
    public EASLoginProxy getEASLogin(WebServiceFeature... features) {
        return super.getPort(new QName("http://10.99.10.62:6888/ormrpc/services/EASLogin", "EASLogin"), EASLoginProxy.class, features);
    }

}
