
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EASLoginProxy", targetNamespace = "http://10.99.10.62:6888/ormrpc/services/EASLogin")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EASLoginProxy {


    /**
     * 
     * @param dcName
     * @param userName
     * @param language
     * @param dbType
     * @param slnName
     * @param ltpaToken
     * @return
     *     returns webservice.WSContext
     */
    @WebMethod
    @WebResult(name = "loginByLtpaTokenReturn", partName = "loginByLtpaTokenReturn")
    public WSContext loginByLtpaToken(
        @WebParam(name = "userName", partName = "userName")
        String userName,
        @WebParam(name = "ltpaToken", partName = "ltpaToken")
        String ltpaToken,
        @WebParam(name = "slnName", partName = "slnName")
        String slnName,
        @WebParam(name = "dcName", partName = "dcName")
        String dcName,
        @WebParam(name = "language", partName = "language")
        String language,
        @WebParam(name = "dbType", partName = "dbType")
        int dbType);

    /**
     * 
     * @param dcName
     * @param userName
     * @param language
     * @param slnName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "logoutReturn", partName = "logoutReturn")
    public boolean logout(
        @WebParam(name = "userName", partName = "userName")
        String userName,
        @WebParam(name = "slnName", partName = "slnName")
        String slnName,
        @WebParam(name = "dcName", partName = "dcName")
        String dcName,
        @WebParam(name = "language", partName = "language")
        String language);

    /**
     * 
     * @param dcName
     * @param userName
     * @param language
     * @param dbType
     * @param slnName
     * @param password
     * @return
     *     returns webservice.WSContext
     */
    @WebMethod
    @WebResult(name = "loginReturn", partName = "loginReturn")
    public WSContext login(
        @WebParam(name = "userName", partName = "userName")
        String userName,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "slnName", partName = "slnName")
        String slnName,
        @WebParam(name = "dcName", partName = "dcName")
        String dcName,
        @WebParam(name = "language", partName = "language")
        String language,
        @WebParam(name = "dbType", partName = "dbType")
        int dbType);

    /**
     * 
     * @param authPattern
     * @param dcName
     * @param userName
     * @param language
     * @param dbType
     * @param slnName
     * @param password
     * @return
     *     returns webservice.WSContext
     */
    @WebMethod
    @WebResult(name = "loginReturn", partName = "loginReturn")
    public WSContext login(
        @WebParam(name = "userName", partName = "userName")
        String userName,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "slnName", partName = "slnName")
        String slnName,
        @WebParam(name = "dcName", partName = "dcName")
        String dcName,
        @WebParam(name = "language", partName = "language")
        String language,
        @WebParam(name = "dbType", partName = "dbType")
        int dbType,
        @WebParam(name = "authPattern", partName = "authPattern")
        String authPattern);

    /**
     * 
     * @param authPattern
     * @param dcName
     * @param isEncodePwd
     * @param userName
     * @param language
     * @param dbType
     * @param slnName
     * @param password
     * @return
     *     returns webservice.WSContext
     */
    @WebMethod
    @WebResult(name = "loginReturn", partName = "loginReturn")
    public WSContext login(
        @WebParam(name = "userName", partName = "userName")
        String userName,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "slnName", partName = "slnName")
        String slnName,
        @WebParam(name = "dcName", partName = "dcName")
        String dcName,
        @WebParam(name = "language", partName = "language")
        String language,
        @WebParam(name = "dbType", partName = "dbType")
        int dbType,
        @WebParam(name = "authPattern", partName = "authPattern")
        String authPattern,
        @WebParam(name = "isEncodePwd", partName = "isEncodePwd")
        int isEncodePwd);

}
