
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSBillInterfaceFacadeSrvProxyService", targetNamespace = "http://10.99.10.62:6888/ormrpc/services/WSBillInterfaceFacade", wsdlLocation = "file:/E:/testDemo/WSBillInterfaceFacade.wsdl")
public class WSBillInterfaceFacadeSrvProxyService
    extends Service
{

    private final static URL WSBILLINTERFACEFACADESRVPROXYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(webservice.WSBillInterfaceFacadeSrvProxyService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = webservice.WSBillInterfaceFacadeSrvProxyService.class.getResource(".");
            url = new URL(baseUrl, "file:/E:/testDemo/WSBillInterfaceFacade.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/E:/testDemo/WSBillInterfaceFacade.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSBILLINTERFACEFACADESRVPROXYSERVICE_WSDL_LOCATION = url;
    }

    public WSBillInterfaceFacadeSrvProxyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSBillInterfaceFacadeSrvProxyService() {
        super(WSBILLINTERFACEFACADESRVPROXYSERVICE_WSDL_LOCATION, new QName("http://10.99.10.62:6888/ormrpc/services/WSBillInterfaceFacade", "WSBillInterfaceFacadeSrvProxyService"));
    }

    /**
     * 
     * @return
     *     returns WSBillInterfaceFacadeSrvProxy
     */
    @WebEndpoint(name = "WSBillInterfaceFacade")
    public WSBillInterfaceFacadeSrvProxy getWSBillInterfaceFacade() {
        return super.getPort(new QName("http://10.99.10.62:6888/ormrpc/services/WSBillInterfaceFacade", "WSBillInterfaceFacade"), WSBillInterfaceFacadeSrvProxy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSBillInterfaceFacadeSrvProxy
     */
    @WebEndpoint(name = "WSBillInterfaceFacade")
    public WSBillInterfaceFacadeSrvProxy getWSBillInterfaceFacade(WebServiceFeature... features) {
        return super.getPort(new QName("http://10.99.10.62:6888/ormrpc/services/WSBillInterfaceFacade", "WSBillInterfaceFacade"), WSBillInterfaceFacadeSrvProxy.class, features);
    }

}
