
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSBillInterfaceFacadeSrvProxy", targetNamespace = "http://10.99.10.62:6888/ormrpc/services/WSBillInterfaceFacade")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSBillInterfaceFacadeSrvProxy {


    /**
     * 
     * @param infoParam
     * @param billTypeCode
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "importBillDataReturn", partName = "importBillDataReturn")
    public String importBillData(
        @WebParam(name = "billTypeCode", partName = "billTypeCode")
        String billTypeCode,
        @WebParam(name = "infoParam", partName = "infoParam")
        String infoParam);

}
