
package ModeDataWebservice.webservicesProd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ModeDateServicePortType", targetNamespace = "http://localhost/services/ModeDateService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ModeDateServicePortType {


    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/ModeDateService")
    @RequestWrapper(localName = "getModeDataByID", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.GetModeDataByID")
    @ResponseWrapper(localName = "getModeDataByIDResponse", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.GetModeDataByIDResponse")
    public String getModeDataByID(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/ModeDateService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/ModeDateService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/ModeDateService")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/ModeDateService")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/ModeDateService")
        String in4);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/ModeDateService")
    @RequestWrapper(localName = "deleteModeDataById", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.DeleteModeDataById")
    @ResponseWrapper(localName = "deleteModeDataByIdResponse", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.DeleteModeDataByIdResponse")
    public String deleteModeDataById(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/ModeDateService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/ModeDateService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/ModeDateService")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/ModeDateService")
        String in3);

    /**
     * 
     * @param in6
     * @param in5
     * @param in7
     * @param in0
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/ModeDateService")
    @RequestWrapper(localName = "getAllModeDataList", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.GetAllModeDataList")
    @ResponseWrapper(localName = "getAllModeDataListResponse", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.GetAllModeDataListResponse")
    public String getAllModeDataList(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/ModeDateService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/ModeDateService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/ModeDateService")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/ModeDateService")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost/services/ModeDateService")
        int in4,
        @WebParam(name = "in5", targetNamespace = "http://localhost/services/ModeDateService")
        String in5,
        @WebParam(name = "in6", targetNamespace = "http://localhost/services/ModeDateService")
        String in6,
        @WebParam(name = "in7", targetNamespace = "http://localhost/services/ModeDateService")
        String in7);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/ModeDateService")
    @RequestWrapper(localName = "saveModeData", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.SaveModeData")
    @ResponseWrapper(localName = "saveModeDataResponse", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.SaveModeDataResponse")
    public String saveModeData(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/ModeDateService")
        String in0);

    /**
     * 
     * @param in0
     * @param in2
     * @param in1
     * @param in3
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://localhost/services/ModeDateService")
    @RequestWrapper(localName = "getAllModeDataCount", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.GetAllModeDataCount")
    @ResponseWrapper(localName = "getAllModeDataCountResponse", targetNamespace = "http://localhost/services/ModeDateService", className = "ModeDataWebservice.webservicesProd.GetAllModeDataCountResponse")
    public int getAllModeDataCount(
        @WebParam(name = "in0", targetNamespace = "http://localhost/services/ModeDateService")
        int in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost/services/ModeDateService")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost/services/ModeDateService")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost/services/ModeDateService")
        String in3);

}
