
package ModeDataWebservice.webservicesProd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ModeDateService", targetNamespace = "http://localhost/services/ModeDateService", wsdlLocation = "https://office.wison.com//services/ModeDateService?wsdl")
public class ModeDateService
    extends Service
{

    private final static URL MODEDATESERVICE_WSDL_LOCATION;
    private final static WebServiceException MODEDATESERVICE_EXCEPTION;
    private final static QName MODEDATESERVICE_QNAME = new QName("http://localhost/services/ModeDateService", "ModeDateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://office.wison.com//services/ModeDateService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MODEDATESERVICE_WSDL_LOCATION = url;
        MODEDATESERVICE_EXCEPTION = e;
    }

    public ModeDateService() {
        super(__getWsdlLocation(), MODEDATESERVICE_QNAME);
    }

    public ModeDateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MODEDATESERVICE_QNAME, features);
    }

    public ModeDateService(URL wsdlLocation) {
        super(wsdlLocation, MODEDATESERVICE_QNAME);
    }

    public ModeDateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MODEDATESERVICE_QNAME, features);
    }

    public ModeDateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ModeDateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ModeDateServicePortType
     */
    @WebEndpoint(name = "ModeDateServiceHttpPort")
    public ModeDateServicePortType getModeDateServiceHttpPort() {
        return super.getPort(new QName("http://localhost/services/ModeDateService", "ModeDateServiceHttpPort"), ModeDateServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ModeDateServicePortType
     */
    @WebEndpoint(name = "ModeDateServiceHttpPort")
    public ModeDateServicePortType getModeDateServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/services/ModeDateService", "ModeDateServiceHttpPort"), ModeDateServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MODEDATESERVICE_EXCEPTION!= null) {
            throw MODEDATESERVICE_EXCEPTION;
        }
        return MODEDATESERVICE_WSDL_LOCATION;
    }

}
